package com.caej.order.domain;

import java.time.LocalDateTime;

import com.caej.order.payment.PaymentMethodView;
import com.caej.order.payment.PaymentStatusView;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

/**
 * @author miller
 */
@Entity(name = "payment_tracking")
public class PaymentTracking {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "payment_id")
    public String paymentId;
    @Field(name = "payment_date")
    public LocalDateTime paymentDate;
    @Field(name = "status")
    public PaymentStatusView status;
    @Field(name = "method")
    public PaymentMethodView method;
    @Field(name = "pay_mode")
    public String payMode;
    @Field(name = "total")
    public Double total;
    @Field(name = "full_name")
    public String fullName;
    @Field(name = "phone")
    public String phone;
    @Field(name = "address")
    public String address;
    @Field(name = "city")
    public String city;
    @Field(name = "province")
    public String province;
    @Field(name = "zip_code")
    public String zipCode;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
    @Field(name = "payment_date_new")
    public LocalDateTime paymentDateNew;
    @Field(name = "status_new")
    public PaymentStatusView statusNew;
    @Field(name = "method_new")
    public PaymentMethodView methodNew;
    @Field(name = "pay_mode_new")
    public String payModeNew;
    @Field(name = "total_new")
    public Double totalNew;
    @Field(name = "full_name_new")
    public String fullNameNew;
    @Field(name = "phone_new")
    public String phoneNew;
    @Field(name = "address_new")
    public String addressNew;
    @Field(name = "city_new")
    public String cityNew;
    @Field(name = "province_new")
    public String provinceNew;
    @Field(name = "zip_code_new")
    public String zipCodeNew;
    @Field(name = "updated_time_new")
    public LocalDateTime updatedTimeNew;
    @Field(name = "updated_by_new")
    public String updatedByNew;
    @Field(name = "pc_out_trade_no")
    public String pcOutTradeNo;
    @Field(name = "type")
    public String type;
    @Field(name = "notify_pay_time")
    public LocalDateTime notifyPayTime;
    @Field(name = "message_detail")
    public String messageDetail;
    @Field(name = "transaction_id")
    public String transactionId;
    @Field(name = "pc_out_trade_no_new")
    public String pcOutTradeNoNew;
    @Field(name = "type_new")
    public String typeNew;
    @Field(name = "notify_pay_time_new")
    public LocalDateTime notifyPayTimeNew;
    @Field(name = "message_detail_new")
    public String messageDetailNew;
    @Field(name = "transaction_id_new")
    public String transactionIdNew;
}
