package io.sited.customer.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "customer_country")
public class Country {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "flag_image_url")
    public String flagImageURL;
    @Field(name = "country_code")
    public String countryCode;
    @Field(name = "display_name")
    public String displayName;
    @Field(name = "currencies")
    public String currencies;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
}
