DROP TABLE IF EXISTS `orders`;
DROP TABLE IF EXISTS `payment`;
DROP TABLE IF EXISTS `payment_tracking`;
DROP TABLE IF EXISTS `order_item`;
DROP TABLE IF EXISTS `credit`;
DROP TABLE IF EXISTS `credit_tracking`;
DROP TABLE IF EXISTS `job_scheduler`;
CREATE TABLE `orders` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `payment_id` varchar(255) DEFAULT NULL,
  `product_id` varchar(255) DEFAULT NULL,
  `vendor_id` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `product_display_name` varchar(255) DEFAULT NULL,
  `product_description` varchar(255) DEFAULT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `dealer_id` varchar(255) DEFAULT NULL,
  `dealer_name` varchar(255) DEFAULT NULL,
  `commission_rate` INT DEFAULT NULL,
  `form` text,
  `price` double DEFAULT NULL,
  `shipping_fee` double DEFAULT NULL,
  `discount` double DEFAULT NULL,
  `total` double DEFAULT NULL,
  `order_date` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `status` varchar(100) DEFAULT NULL,
  `shipping_status` varchar(100) DEFAULT NULL,
  `updated_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `period_display_name` varchar(255) DEFAULT NULL,
  `period_unit` varchar(255) DEFAULT NULL,
  `period_value` int(11) DEFAULT NULL,
  `unit` varchar(255) DEFAULT NULL,
  `trans_no` varchar(255) DEFAULT NULL,
  `trans_type` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  `errors` text DEFAULT NULL,
  `plan_start_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `out_trade_no` varchar(255) DEFAULT NULL,
  `apply_code` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `insured_name` varchar(255) DEFAULT NULL,
  `insured_id_type` varchar(255) DEFAULT NULL,
  `insured_id_number` varchar(255) DEFAULT NULL,
  `insured_phone` varchar(255) DEFAULT NULL,
  `insured_email` varchar(255) DEFAULT NULL,
  `policy_holder_name` varchar(255) DEFAULT NULL,
  `policy_holder_id_type` varchar(255) DEFAULT NULL,
  `policy_holder_id_number` varchar(255) DEFAULT NULL,
  `policy_holder_phone` varchar(255) DEFAULT NULL,
  `policy_holder_email` varchar(255) DEFAULT NULL,
  `archive_url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payment` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `payment_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `status` varchar(100) DEFAULT NULL,
  `method` varchar(100) DEFAULT NULL,
  `pay_mode` varchar(255) DEFAULT NULL,
  `total` double DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `updated_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by` varchar(255) DEFAULT NULL,
  `created_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `created_by` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  `out_trade_no` varchar(255) DEFAULT NULL,
  `bill_id` varchar(255) DEFAULT NULL,
  `bill_url` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `optional` text,
  `return_url` varchar(255) DEFAULT NULL,
  `notify_url` varchar(255) DEFAULT NULL,
  `timeout` int(11) DEFAULT NULL,
  `limit_pay` varchar(255) DEFAULT NULL,
  `pc_pay` varchar(255) DEFAULT NULL,
  `open_id` varchar(255) DEFAULT NULL,
  `show_url` varchar(255) DEFAULT NULL,
  `qr_code_mode` varchar(255) DEFAULT NULL,
  `qr_code_width` varchar(255) DEFAULT NULL,
  `sign` varchar(255) DEFAULT NULL,
  `pay_timestamp` bigint(20) DEFAULT NULL,
  `code_url` text,
  `qr_code` text,
  `pay_url` text,
  `to_pay_error` text,
  `pc_out_trade_no` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `notify_pay_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `message_detail` text,
  `transaction_id` varchar(255) DEFAULT NULL,
  `customer_id` varchar(255) DEFAULT NULL,
  `latest_effect_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `payment_tracking` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `payment_id` varchar(255) DEFAULT NULL,
  `payment_date` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `status` varchar(100) DEFAULT NULL,
  `method` varchar(100) DEFAULT NULL,
  `pay_mode` varchar(255) DEFAULT NULL,
  `total` double DEFAULT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `province` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `updated_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by` varchar(255) DEFAULT NULL,
  `payment_date_new` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `status_new` varchar(100) DEFAULT NULL,
  `method_new` varchar(100) DEFAULT NULL,
  `pay_mode_new` varchar(255) DEFAULT NULL,
  `total_new` double DEFAULT NULL,
  `full_name_new` varchar(255) DEFAULT NULL,
  `phone_new` varchar(255) DEFAULT NULL,
  `address_new` varchar(255) DEFAULT NULL,
  `city_new` varchar(255) DEFAULT NULL,
  `province_new` varchar(255) DEFAULT NULL,
  `zip_code_new` varchar(255) DEFAULT NULL,
  `updated_time_new` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by_new` varchar(255) DEFAULT NULL,
  `pc_out_trade_no` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `notify_pay_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `message_detail` text,
  `transaction_id` varchar(255) DEFAULT NULL,
  `pc_out_trade_no_new` varchar(255) DEFAULT NULL,
  `type_new` varchar(255) DEFAULT NULL,
  `notify_pay_time_new` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `message_detail_new` text,
  `transaction_id_new` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `order_item` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `order_id` varchar(255) DEFAULT NULL,
  `form` text,
  `name` varchar(255) DEFAULT NULL,
  `price` double DEFAULT NULL,
  `order_status` varchar(100) DEFAULT NULL,
  `order_date` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `updated_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by` varchar(255) DEFAULT NULL,
  `created_by` varchar(255) DEFAULT NULL,
  `policy_code` varchar(255) DEFAULT NULL,
  `policy_address` varchar(255) DEFAULT NULL,
  `refund_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `credit` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `dealer_id` varchar(30) DEFAULT NULL,
  `total_credits` double DEFAULT NULL,
  `quota` double DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  `created_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `created_by` varchar(255) DEFAULT NULL,
  `updated_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00',
  `updated_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `credit_tracking` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `credit_id` varchar(255) DEFAULT NULL,
  `payment_id` varchar(255) DEFAULT NULL,
  `quota` double DEFAULT NULL,
  `type` varchar(10) DEFAULT NULL,
  `total_credits` double DEFAULT NULL,
  `operator` varchar(255) DEFAULT NULL,
  `created_time` timestamp NOT NULL DEFAULT '1970-01-02 00:00:00' ,
  `created_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `job_scheduler` (
  `id` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(255) DEFAULT NULL,
  `status` varchar(100) DEFAULT NULL,
  `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_error` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `job_scheduler` VALUES ('paymentTimeout', 'paymentTimeout', 'WAITING', '2017-1-5 15:07:26', NULL);
INSERT INTO `job_scheduler` VALUES ('queryOrderStatus', 'queryOrderStatus', 'WAITING', '2017-1-5 15:07:26', NULL);
INSERT INTO `job_scheduler` VALUES ('underwriting', 'underwriting', 'WAITING', '2017-1-5 15:07:26', NULL);
INSERT INTO `job_scheduler` VALUES ('orderArchive', 'orderArchive', 'WAITING', '2017-1-5 15:07:26', NULL);