package io.sited.customer.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * @author miller
 */
@Entity(name = "customer_customer")
public class Customer {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "identification")
    public String identification;
    @Field(name = "identification_type")
    public String identificationType;
    @Field(name = "country_code")
    public String countryCode;
    @Field(name = "currency_code")
    public String currencyCode;
    @Field(name = "state")
    public String state;
    @Field(name = "city")
    public String city;
    @Field(name = "ward")
    public String ward;
    @Field(name = "birthday")
    public LocalDate birthday;
    @Field(name = "gender")
    public Gender gender;
    @Field(name = "channel_id")
    public String channelId;
    @Field(name = "campaign_id")
    public String campaignId;
    @Field(name = "source")
    public String source;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
}
