package app.dealer.credit.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author Jonathan.Guo
 */
@Entity(name = "credit_tracking")
public class CreditTracking {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "credit_id")
    public String creditId;
    @Field(name = "payment_id")
    public String paymentId;
    @Field(name = "quota")
    public Double quota;
    @Field(name = "type")
    public UpdateCreditType type;
    @Field(name = "total_credits")
    public Double totalCredits;
    @Field(name = "operator")
    public String operator;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
}
