package io.sited.db.impl.jdbc;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

/**
 * @author chi
 */
@Entity(name = "test_entity2")
public class TestEntity2 {
    @Id(autoGenerated = false)
    public String id;

    @Field(name = "name")
    public String name;
}

