package io.sited.user.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "user_pin_code_tracking")
public class UserPinCodeTracking {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "email")
    public String email;
    @Field(name = "phone")
    public String phone;
    @Field(name = "ip")
    public String ip;
    @Field(name = "code")
    public String code;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
}
