package io.sited.user.domain;


import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "user_role")
public class Role {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "name")
    public String name;
    @Field(name = "display_name")
    public String displayName;
    @Field(name = "description")
    public String description;
    @Field(name = "permissions")
    public String permissions;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
}
