package io.sited.customer.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "customer_address")
public class Address {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "customer_id")
    public String customerId;
    @Field(name = "full_name")
    public String fullName;
    @Field(name = "phone")
    public String phone;
    @Field(name = "country_code")
    public String countryCode;
    @Field(name = "state")
    public String state;
    @Field(name = "city")
    public String city;
    @Field(name = "ward")
    public String ward;
    @Field(name = "address1")
    public String address1;
    @Field(name = "address2")
    public String address2;
    @Field(name = "zip_code")
    public String zipCode;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
}
