package com.caej.scheduler.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author miller
 */
@Entity(name = "job_scheduler")
public class JobScheduler {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "name")
    public String name;
    @Field(name = "status")
    public JobSchedulerStatus status;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "last_error")
    public String lastError;
}
