package io.sited.user.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "user_reset_password_token")
public class ResetPasswordToken {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "user_id")
    public String userId;
    @Field(name = "token")
    public String token;
    @Field(name = "status")
    public ResetPasswordTokenStatus status;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
}
