package io.sited.user.domain;

import io.sited.db.Entity;
import io.sited.db.Field;
import io.sited.db.Id;

import java.time.LocalDateTime;

/**
 * @author chi
 */
@Entity(name = "user_user")
public class User {
    @Id(autoGenerated = false)
    public String id;
    @Field(name = "username")
    public String username;
    @Field(name = "full_name")
    public String fullName;
    @Field(name = "description")
    public String description;
    @Field(name = "phone")
    public String phone;
    @Field(name = "email")
    public String email;
    @Field(name = "image_url")
    public String imageURL;
    @Field(name = "roles")
    public String roles;
    @Field(name = "fields")
    public String fields;
    @Field(name = "salt")
    public String salt;
    @Field(name = "iteration")
    public Integer iteration;
    @Field(name = "hashed_password")
    public String hashedPassword;
    @Field(name = "provider")
    public String provider;
    @Field(name = "status")
    public UserStatus status;
    @Field(name = "created_time")
    public LocalDateTime createdTime;
    @Field(name = "created_by")
    public String createdBy;
    @Field(name = "updated_time")
    public LocalDateTime updatedTime;
    @Field(name = "updated_by")
    public String updatedBy;
}
